
DROP TABLE MEMBER;
DROP TABLE CHAT_MESSAGE;
DROP TABLE CHAT_ROOM;
DROP TABLE CHAT_ROOM_JOIN;


DROP SEQUENCE SEQ_UNO;
DROP SEQUENCE SEQ_RNO;
CREATE SEQUENCE SEQ_UNO NOCACHE;
CREATE SEQUENCE SEQ_CM_NO NOCACHE;
CREATE SEQUENCE SEQ_CRM_NO NOCACHE;

CREATE TABLE MEMBER (
  USER_NO NUMBER PRIMARY KEY,               
  EMAIL VARCHAR2(30) NOT NULL UNIQUE,   
  USER_PWD VARCHAR2(100) NOT NULL,  
  NICK_NAME VARCHAR2(15) NOT NULL,    
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
  PROFILE VARCHAR2(200)
);

INSERT INTO MEMBER 
VALUES(
  SEQ_UNO.NEXTVAL,
  'sample1@naver.com',
  1234,
  '루피1',
  DEFAULT,
  DEFAULT,
  DEFAULT,
  '/images/user0.jpg'
);

INSERT INTO MEMBER 
VALUES(
  SEQ_UNO.NEXTVAL,
  'sample2@naver.com',
  1234,
  '루피2',
  DEFAULT,
  DEFAULT,
  DEFAULT,
  '/images/user1.jpg'
);
INSERT INTO MEMBER 
VALUES(
  SEQ_UNO.NEXTVAL,
  'sample3@naver.com',
  1234,
  '루피3',
  DEFAULT,
  DEFAULT,
  DEFAULT,
  '/images/user2.jpg'
);
INSERT INTO MEMBER 
VALUES(
  SEQ_UNO.NEXTVAL,
  'sample4@naver.com',
  1234,
  '루피4',
  DEFAULT,
  DEFAULT,
  DEFAULT,
  '/images/user3.jpg'
);
INSERT INTO MEMBER 
VALUES(
  SEQ_UNO.NEXTVAL,
  'sample5@naver.com',
  1234,
  '루피5',
  DEFAULT,
  DEFAULT,
  DEFAULT,
  '/images/user4.jpg'
);
INSERT INTO MEMBER 
VALUES(
  SEQ_UNO.NEXTVAL,
  'sample6@naver.com',
  1234,
  '루피6',
  DEFAULT,
  DEFAULT,
  DEFAULT,
  '/images/user5.jpg'
);



CREATE TABLE CHAT_MESSAGE(
CM_NO NUMBER PRIMARY KEY,
MESSAGE VARCHAR2(4000),
CREATE_DATE DATE,
CHAT_ROOM_NO NUMBER,
USER_NO NUMBER
);



CREATE TABLE CHAT_ROOM(
    CHAT_ROOM_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(400),
    STATUS VARCHAR2(1) DEFAULT 'Y',
    USER_NO NUMBER
);



CREATE TABLE CHAT_ROOM_JOIN(
    USER_NO NUMBER,
    CHAT_ROOM_NO NUMBER,
    USER_STATUS NUMBER,
    PRIMARY KEY(USER_NO, CHAT_ROOM_NO)
);

COMMIT;


COMMIT;

DELETE FROM CHAT_ROOM_JOIN