CREATE TABLE MEMBER (
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR2(15) UNIQUE NOT NULL,
    USERPWD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    GENDER CHAR(1) CHECK(GENDER IN ('M', 'F')),
    AGE NUMBER,
    EMAIL VARCHAR2(30),
    PHONE CHAR(11),
    ADDRESS VARCHAR2(100),
    HOBBY VARCHAR2(50),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL
);
DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;
INSERT INTO MEMBER VALUES(SEQ_USERNO.NEXTVAL, 'admin', '1234','관리자','M',45,'admin@naver.com', '01012345678','서울','등산', SYSDATE);
COMMIT;

SELECT * FROM MEMBER;

SELECT * FROM MEMBER WHERE LIKE %keyword%

DELETE FROM MEMBER
WHERE USERID = 'gab';

SELECT SEQ_USERNO.NEXTVAL FROM DUAL;

select SEQ_USERNO.currVAL from dual;

SELECT * FROM USER_SEQUENCES;