SELECT BOARD_NO, 
       CATEGORY_NAME, 
       BOARD_TITLE, 
       USER_ID, 
       COUNT, 
       CREATE_DATE
FROM BOARD B
LEFT JOIN CATEGORY USING (CATEGORY_NO)
JOIN MEMBER ON (BOARD_WRITER = USER_NO)
WHERE BOARD_TYPE = 1  
  AND B.STATUS = 'Y'
ORDER BY BOARD_NO DESC  ;

BEGIN
FOR I IN 1..2000
LOOP
INSERT INTO BOARD VALUES
(SEQ_BNO.NEXTVAL, 1, 10, '게시글제목' || 1, '게시글 내용' || 1, 3, default, default, default);
END LOOP;
END;
/
COMMIT;


SELECT *
		FROM(
			SELECT ROWNUM RNUM, A.*
			FROM(
				SELECT BOARD_NO, 
					   CATEGORY_NAME, 
					   BOARD_TITLE, 
					   USER_ID, 
					   COUNT, 
					   CREATE_DATE
				FROM BOARD B
				LEFT JOIN CATEGORY USING (CATEGORY_NO)
				JOIN MEMBER ON (BOARD_WRITER = USER_NO)
				WHERE BOARD_TYPE = 1    <!-- 1:일반게시글 -->
				  AND B.STATUS = 'Y'
				ORDER BY BOARD_NO DESC
			) A
		)
		WHERE RNUM BETWEEN 2 AND 4
/
SELECT *
		FROM(
			SELECT ROWNUM RNUM, A.*
			FROM(
				SELECT BOARD_NO, 
					   CATEGORY_NAME, 
					   BOARD_TITLE, 
					   USER_ID, 
					   COUNT, 
					   CREATE_DATE
				FROM BOARD B
				LEFT JOIN CATEGORY USING (CATEGORY_NO)
				JOIN MEMBER ON (BOARD_WRITER = USER_NO)
				WHERE BOARD_TYPE = 1  
				  AND B.STATUS = 'Y'
				ORDER BY BOARD_NO DESC
			) A
		)
		WHERE RNUM BETWEEN 11 AND 20;
 /    

 SELECT EMAIL
FROM MEMBER      
WHERE EMAIL LIKE '%?@%%' ESCAPE '?'   ;     
   
   /     
  SELECT 
			CATEGORY_NAME,
			BOARD_TITLE,
			USER_ID,
			BOARD_CONTENT,
			CREATE_DATE,
			BOARD_NO
		FROM BOARD B
		LEFT JOIN CATEGORY USING (CATEGORY_NO)
		JOIN MEMBER ON (BOARD_WRITER = USER_NO)
		WHERE BOARD_NO = 1050
		  AND B.STATUS = 'Y'     ;
   /
   
			
	
       
        
        